name: Run Scripts in Sequence

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run first script (RunIntegrationTests)
        run: |
          cd C:\Users\HP\AndroidStudioProjects\EpicDiceEvents_1.4\Automation
          RunIntegrationTests
        continue-on-error: false

      - name: Run second script (adb pull)
        run: |
          cd C:\Users\HP\AndroidStudioProjects\EpicDiceEvents_1.4\Automation
          SaveReport.bat
        continue-on-error: false